<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_chevron_right</name>
   <tag></tag>
   <elementGuidId>87909479-5896-4fa7-b32b-2d44f255abfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='membershipsDiv']/crud-panel/div/div/list/ul/li[4]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.waves-effect > a > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;chevron_right&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6aa757ef-ada3-461b-a46d-b90d2f158c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>f5eb40d3-44ee-4360-b209-e4a98c4d7799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chevron_right</value>
      <webElementGuid>7d168ccf-13e9-4f15-bf40-924488ac76ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membershipsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;waves-effect&quot;]/a[1]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>379685c5-9e38-4ff2-b810-0f20c4d59b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='membershipsDiv']/crud-panel/div/div/list/ul/li[4]/a/i</value>
      <webElementGuid>67fe95e4-a7d4-42b8-8d1a-2bcf34795a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/following::i[1]</value>
      <webElementGuid>afc3358f-3fc6-4803-ae6c-3494c81e25a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[1]/following::i[1]</value>
      <webElementGuid>4d66d943-74b1-46da-b50c-1e24856fec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[1]/preceding::i[1]</value>
      <webElementGuid>9145b981-c851-4554-904c-4adffd2c6ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='chevron_right']/parent::*</value>
      <webElementGuid>34975a5e-83c9-43b1-8c86-309948502e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/i</value>
      <webElementGuid>5d08791a-0ae0-45cc-a89c-cc84d83da508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'chevron_right' or . = 'chevron_right')]</value>
      <webElementGuid>227ec099-ec4c-4d86-bad1-3982d731bee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
