<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select-dropdown active</name>
   <tag></tag>
   <elementGuidId>de0fc2ce-a404-4fdd-901d-679def8a4f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='50']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-dropdown.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#membershipsDiv >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>273b6e1e-e78c-4703-9868-e09bf74dbd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e33dae4a-e67b-448d-8949-b84247ae38fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown active</value>
      <webElementGuid>83482a4c-23cc-432a-99f7-406fc927e8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fd207f1-543a-4d68-ba6f-184232558c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-ec784539-f1d1-b866-335f-5660c1742223</value>
      <webElementGuid>af6e1888-9a71-4910-abd3-d606ffebfeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>30c1c7a5-01a1-4023-9692-7ecaf6cab35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membershipsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-size&quot;]/div[@class=&quot;select-wrapper&quot;]/input[@class=&quot;select-dropdown active&quot;]</value>
      <webElementGuid>4c25e3bb-9ad7-4c10-a359-5709cb8f982c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='50']</value>
      <webElementGuid>e10725fa-46de-4e16-851a-a253a2fb1499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='membershipsDiv']/crud-panel/div/div/list/ul/li[2]/div/input</value>
      <webElementGuid>bac1aad8-a7b6-4c0c-8614-97df74beba5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>70e30bf6-af3c-46f8-8cc5-69b929adf7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>402f5178-a69a-4d79-bdd5-74b2f6f19b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
