<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Membership   arrow_upward</name>
   <tag></tag>
   <elementGuidId>fb4b1da8-3c30-44c5-bac9-424afc2e7368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='membershipsDiv']/crud-panel/div/div/list/table/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.row-name.sortable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Membership arrow_upward&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>313aacbf-f690-483a-8a0f-db501e9f8547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>listField in listData.listFields</value>
      <webElementGuid>1be51e6c-42fc-4fc2-9f0f-0685fcbee060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>memberships</value>
      <webElementGuid>9369e329-48fc-4a36-92ca-3ff7276f9f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1c3e1b2d-bd21-46b0-9746-7e993e5ee724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>list.fetchData(listField.name, listField.sortAction, listField.sortable, listData.pagination)</value>
      <webElementGuid>2320becb-52d8-447f-b410-d9cc047d7c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-name sortable</value>
      <webElementGuid>cc35fc43-10f3-4d0c-8944-43183e9aba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{sortable: listField.sortable}</value>
      <webElementGuid>894dfd22-50bd-45df-bb8e-26ba1123775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>(listField.hideField==true?false:true) &amp;&amp; (listField.hideHeader==true?false:true)</value>
      <webElementGuid>bfeaa7f0-580e-4845-ba28-f439c28e78d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Membership   arrow_upward</value>
      <webElementGuid>fb67812d-45db-4bfb-8c1c-51d116052ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membershipsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;row-name sortable&quot;]</value>
      <webElementGuid>05629f8c-145b-445f-8ec2-0a4125e72f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='membershipsDiv']/crud-panel/div/div/list/table/thead/tr/th[2]</value>
      <webElementGuid>b64f7d1e-c572-4792-bf4d-c0ce0f7857ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::th[1]</value>
      <webElementGuid>b9e593e8-def8-48d4-a0f7-9edc5784a546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_horiz'])[1]/following::th[1]</value>
      <webElementGuid>aef6a5dd-6a87-4ceb-881b-28341b130884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AELL Membership'])[1]/preceding::th[2]</value>
      <webElementGuid>93ecc853-6335-4213-9f04-c40dc3c39d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Membership']/parent::*</value>
      <webElementGuid>14a09739-2721-4b84-a891-0c8ad1c18829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>63bb6084-7502-4467-8ce2-5c05c19a49b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Membership   arrow_upward' or . = 'Membership   arrow_upward')]</value>
      <webElementGuid>5d0187f6-6e9d-41f0-88ff-9e9c22540338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
