<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_more_horiz</name>
   <tag></tag>
   <elementGuidId>b02b3075-d91f-4cdf-b633-4e9d872236ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.icons-color.orange-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;more_horiz&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aeac47b0-23a3-4675-9e80-6f72ea5b31ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons icons-color orange-text</value>
      <webElementGuid>c2d4c2f2-8711-4c9d-a355-a55de550ae8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'orange-text': listData.selected.length > 0}</value>
      <webElementGuid>26c4a091-7e95-467e-8c07-5b0bc246b739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horiz</value>
      <webElementGuid>3b9f54a1-94e6-4950-96d5-6a9ed2ac1ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employmentStatusDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;list-options&quot;]/a[@class=&quot;dropdown-button dropdown&quot;]/i[@class=&quot;material-icons icons-color orange-text&quot;]</value>
      <webElementGuid>0146e8c8-b0d4-4103-9d52-b0897e8d3882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/thead/tr/th/a/i</value>
      <webElementGuid>26906bc5-4a3a-4f80-9616-328849b0697f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::i[1]</value>
      <webElementGuid>0aee2e24-b368-4535-ab31-09949c555829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::i[1]</value>
      <webElementGuid>0c519eb3-2a52-45a2-b13e-9d6f7cd1c4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::i[1]</value>
      <webElementGuid>44bd6851-00b1-4d20-b14f-40b43390ff4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[1]/preceding::i[1]</value>
      <webElementGuid>0a428bb0-b244-41f9-a70e-aa27a4d3dca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_horiz']/parent::*</value>
      <webElementGuid>5e41e4c6-17d8-4f2c-b9d6-13be533dc118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a/i</value>
      <webElementGuid>d184d8bd-b900-4bf8-a1e4-263edac14b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'more_horiz' or . = 'more_horiz')]</value>
      <webElementGuid>a693d417-ed2d-445b-9a24-5df1bf226351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
