<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ohrm_edit</name>
   <tag></tag>
   <elementGuidId>59e85a2a-3da0-47ed-86b2-4189cda55d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.edit_item.tooltipped > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Part-Time Regular ohrm_edit&quot;i] >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a30acdd3-eb74-4577-a439-dca74c212850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>TD.class=='edit_item'?true:false</value>
      <webElementGuid>47ccbe6a-8d5b-4da5-aec6-a62b48986014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>030f64f4-73bf-4859-9dbd-446adbce4614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ohrm_edit</value>
      <webElementGuid>a189699e-445e-4c7b-9c6e-95495bec0883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employmentStatusDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[@class=&quot;edit_item tooltipped&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>f07177cd-f781-4251-89b6-048bad2b3d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      <webElementGuid>b4ed63b0-4387-492d-b4cd-62c50e4a0153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part-Time Regular'])[1]/following::i[1]</value>
      <webElementGuid>bb8f25aa-9d3a-4531-ac7e-e772c42837bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_downward'])[1]/following::i[1]</value>
      <webElementGuid>d79f7e50-4145-459c-99df-b158548f9db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::i[1]</value>
      <webElementGuid>1976ee6f-e465-4498-8aa9-3d6f5b8d45ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part-Time Permanent'])[1]/preceding::i[1]</value>
      <webElementGuid>a49db8e0-6d42-4dc8-abf0-03b7e04b3b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ohrm_edit']/parent::*</value>
      <webElementGuid>a236757a-9738-445b-8774-007547b5e9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/i</value>
      <webElementGuid>74cb66ad-92cd-4697-952c-09ba696a608c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'ohrm_edit' or . = 'ohrm_edit')]</value>
      <webElementGuid>f864eac8-fc36-4ed9-a739-7b68ef59b4ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
