<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ohrm_edit</name>
   <tag></tag>
   <elementGuidId>9b7d362f-a55a-4467-b798-15c821e4d0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.edit_item.tooltipped</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;test ohrm_edit&quot;i] >> internal:role=cell >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e101757c-50ea-45c6-b84a-15af57fda4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>TD in listData.extraTD</value>
      <webElementGuid>9bf78112-15ec-4f84-9f94-b6fa8126ceeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit_item tooltipped</value>
      <webElementGuid>5d0f97da-931d-4620-8336-e27eb21410f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>list.runAction(TD.clickAction, obj)</value>
      <webElementGuid>9395ed45-98c1-4b69-b20c-3ffc57588c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>TD.hideIf === undefined || TD.hideIf(obj)</value>
      <webElementGuid>bf0fa042-c9c7-44f3-bf1a-e5cfa9e1b258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c9a4c92-b872-4c9d-bdfc-a6c4285a8bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>b9a7ae89-a7a9-476c-8c31-8dc3f5ee7abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>c6064ecb-a6dd-4f45-a4b4-30412d807031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-id</name>
      <type>Main</type>
      <value>19bc1942-1ed3-24d6-6ade-333a8546c808</value>
      <webElementGuid>ac57b8ba-23bf-44a3-aa5d-a904018a7b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ohrm_edit </value>
      <webElementGuid>10b45cfc-727a-40e2-805d-6c3a6408519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employmentStatusDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[@class=&quot;edit_item tooltipped&quot;]</value>
      <webElementGuid>bcd35821-b555-49ae-b165-2c855291dac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employmentStatusDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]</value>
      <webElementGuid>defde28f-5170-4e79-b715-2aa711667de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::td[1]</value>
      <webElementGuid>11707b82-984b-4d51-9e8f-3873b22028af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::td[3]</value>
      <webElementGuid>e2597fcc-0103-4a8b-afb6-6076558c8a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::td[1]</value>
      <webElementGuid>39d37f24-6924-4757-9ace-7554efe411be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>612cf7b3-2e21-49da-b1d2-5932c6bfcb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ohrm_edit ' or . = 'ohrm_edit ')]</value>
      <webElementGuid>27649e46-8a34-47f2-ab42-9dd53dcb0e24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
