<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Pay Grade Name Already exists</name>
   <tag></tag>
   <elementGuidId>3b5c2b32-881d-4acc-af53-5b8d6bcd21cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Add Pay Grade Name* Already exists* Required fieldSave Cancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47451c96-814c-4da4-8873-c6ba95f7e5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal1</value>
      <webElementGuid>2f61fd09-b650-4fd9-a9bc-477e0b0b4092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal modal-fixed-footer open</value>
      <webElementGuid>d9e73e77-6a19-4aca-9b1c-ab55a159624a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Pay Grade Name* Already exists* Required fieldSave Cancel</value>
      <webElementGuid>0a924e7d-b822-4bdb-8dd1-5fadc9e52da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)</value>
      <webElementGuid>6ddd3ae5-c8ce-4d66-9b50-9f60ef7d3939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modal1']</value>
      <webElementGuid>6837acdf-b03a-4c92-9c55-c863271dfc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{(list.getTDTooltip(TD.tooltip, obj)) | translate}}'])[8]/following::div[2]</value>
      <webElementGuid>d9faf2d0-9c0b-4516-a16f-dd10b34780b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{(list.getTDTooltip(TD.tooltip, obj)) | translate}}'])[7]/following::div[4]</value>
      <webElementGuid>22464ac2-b008-4d0e-ac6e-e9622c4ccb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[51]</value>
      <webElementGuid>83620c47-daa1-49ee-9ab0-9208c4423653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'modal1' and (text() = 'Add Pay Grade Name* Already exists* Required fieldSave Cancel' or . = 'Add Pay Grade Name* Already exists* Required fieldSave Cancel')]</value>
      <webElementGuid>e7f214f4-5c7a-456c-9f77-e010c58e2cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
