<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Pay Grade Name Required field</name>
   <tag></tag>
   <elementGuidId>133f41cf-6c7a-4b53-8cbe-9fdad30a1c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Add Pay Grade Name* * Required fieldSave Cancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bcd4fa2-f397-4d73-b3e6-6ef29af60642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal1</value>
      <webElementGuid>623fb2ce-c394-432a-94af-710f3d2e0175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal modal-fixed-footer open</value>
      <webElementGuid>dda0b824-47e1-403f-a015-e606b285bcff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Pay Grade Name* * Required fieldSave Cancel</value>
      <webElementGuid>4b975aac-7843-4f5e-9dbc-0f052ab7ac14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)</value>
      <webElementGuid>ce0bc983-4f98-44f3-8c26-032f7630aa37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modal1']</value>
      <webElementGuid>a670fe63-a971-4df9-a0cd-d46b120c3a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{(list.getTDTooltip(TD.tooltip, obj)) | translate}}'])[8]/following::div[2]</value>
      <webElementGuid>df4f2f0c-32d4-4073-87f4-e035982a381b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{(list.getTDTooltip(TD.tooltip, obj)) | translate}}'])[7]/following::div[4]</value>
      <webElementGuid>c8de687a-b266-4bce-a470-e2d5c4dfaaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[51]</value>
      <webElementGuid>e4b6e190-2d51-4c0a-bc0e-fb77274f46f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'modal1' and (text() = 'Add Pay Grade Name* * Required fieldSave Cancel' or . = 'Add Pay Grade Name* * Required fieldSave Cancel')]</value>
      <webElementGuid>1ad18fda-d552-4c37-b6a7-6a6be5d954ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
