<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assign currency Button</name>
   <tag></tag>
   <elementGuidId>403fd19c-8ac1-4dcb-9eee-4daddc7ce4fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sf-decorator:nth-of-type(3) > div.form-group.schema-form-submit.right > button.btn.waves-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Assign currency&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cebcaa8f-1245-4682-a554-650329c84b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn waves-effect </value>
      <webElementGuid>536bc84f-8726-4fd8-ba17-8f82301b421b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dfcb7b8-fdd3-47dd-898f-dc8159c4b284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>buttonClick($event,form)</value>
      <webElementGuid>e3663212-a3c6-4b55-b809-91ac646af67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>8eb160df-d45d-4c03-aba4-d3d2b0daa2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>form.type !== 'submit'</value>
      <webElementGuid>100494bd-e7e9-44c3-aa32-3a84cff6b191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign currency</value>
      <webElementGuid>04e94c19-8d3d-42f4-972d-c92dd571a173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_details_tab&quot;)/form[@class=&quot;ng-pristine ng-valid ng-valid-duplication-pay-grades ng-valid-schema-form&quot;]/materializecss-decorator[3]/div[@class=&quot;schema-form-section row form-buttons&quot;]/sf-decorator[3]/div[@class=&quot;form-group schema-form-submit right&quot;]/button[@class=&quot;btn waves-effect&quot;]</value>
      <webElementGuid>186974ff-6203-424b-ba02-b8f41dce9210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>07cf2526-7ac8-48c3-9d3d-21e5a48efc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_details_tab']/form/materializecss-decorator[3]/div/sf-decorator[3]/div/button</value>
      <webElementGuid>903e0c26-c70a-44ea-8040-6ed9e1b49750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>e54de08d-0a84-4d9d-ae65-b3b117fd90a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[2]</value>
      <webElementGuid>cfb13d60-0856-4dbc-954a-0d8e3dacb339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_horiz'])[1]/preceding::button[1]</value>
      <webElementGuid>331dc7d4-e72c-420c-9f1a-6baaafa61178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::button[1]</value>
      <webElementGuid>d6a9089f-87d5-41cc-a7a0-5cdccd4097e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assign currency']/parent::*</value>
      <webElementGuid>2b65d95b-c7b4-45b1-8a47-b7e2160dd622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator[3]/div/button</value>
      <webElementGuid>022691ef-ca1c-431e-8865-5bdb3c22eef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Assign currency' or . = 'Assign currency')]</value>
      <webElementGuid>cf250ccb-97ac-4e1f-8fca-9b7decd63857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
