<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Maximum Salary</name>
   <tag></tag>
   <elementGuidId>976a35a4-503a-4f43-9985-037a593ee3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div/div/materializecss-decorator[3]/div/sf-decorator/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>materializecss-decorator:nth-of-type(3) > div.schema-form-section.row > sf-decorator > div.input-field.col.s12.m12.l12 > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal1 >> internal:text=&quot;Maximum Salary&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>02aa3aab-a97c-4ac5-9d8d-23631ecbeb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>maxSalary</value>
      <webElementGuid>e2a8ddb9-0481-4f54-9fa7-5757a7a49b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!form.hideLabel</value>
      <webElementGuid>b4403a17-a60b-4226-8ef1-dbc17a1cf0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maximum Salary</value>
      <webElementGuid>7c9b6bf2-ab6a-4571-8582-0076f3181e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-valid-max ng-dirty ng-valid-parse ng-valid-lower-than-minimum ng-valid-numeric-positive ng-valid ng-valid-schema-form&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/materializecss-decorator[3]/div[@class=&quot;schema-form-section row&quot;]/sf-decorator[1]/div[@class=&quot;input-field col s12 m12 l12&quot;]/label[1]</value>
      <webElementGuid>7c498f6c-20da-4d28-bc80-4418ee252448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div/div/materializecss-decorator[3]/div/sf-decorator/div/label</value>
      <webElementGuid>2360fe11-2b39-4c49-83e6-354e34b216b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Salary'])[2]/following::label[1]</value>
      <webElementGuid>72b4070c-0546-426d-a5fe-f620ba692311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[2]</value>
      <webElementGuid>cc11d147-7618-479e-bc08-3d7843615f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::label[1]</value>
      <webElementGuid>ce95625e-a958-4ebe-a1db-1d75af81eb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//materializecss-decorator[3]/div/sf-decorator/div/label</value>
      <webElementGuid>7ba579a1-c955-4bc0-8299-162ea60280a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Maximum Salary' or . = 'Maximum Salary')]</value>
      <webElementGuid>2b042dfb-0dfd-4389-b50f-b82194441879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
