<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Should be a positive number with at mo_91f26e</name>
   <tag></tag>
   <elementGuidId>a4918077-2b03-4cdd-9da3-86a7c345f353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div/div/materializecss-decorator[2]/div/sf-decorator/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>materializecss-decorator:nth-of-type(2) > div.schema-form-section.row > sf-decorator > div.input-field.col.s12.m12.l12 > span.help-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Should be a positive number with at most 2 decimal places&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6c0fd26-b95b-4532-8cc1-7a4b73ce83ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>f5189d44-1340-4053-b409-d53aebf99eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-message</name>
      <type>Main</type>
      <value>form.description</value>
      <webElementGuid>ffe5b414-b953-43a2-b135-48ad51777e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Should be a positive number with at most 2 decimal places</value>
      <webElementGuid>ce8e5260-e812-47e8-8f32-46418639ea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-dirty ng-valid-parse ng-valid-lower-than-minimum ng-invalid ng-invalid-numeric-positive ng-invalid-max ng-invalid-schema-form&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/materializecss-decorator[2]/div[@class=&quot;schema-form-section row&quot;]/sf-decorator[1]/div[@class=&quot;input-field col s12 m12 l12&quot;]/span[@class=&quot;help-block&quot;]</value>
      <webElementGuid>35113190-f131-47eb-97d2-6a77dc4ece3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div/div/materializecss-decorator[2]/div/sf-decorator/div/span</value>
      <webElementGuid>36dba84e-7eea-4c89-9695-7578e9421ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Salary'])[2]/following::span[1]</value>
      <webElementGuid>0349ca28-0fa6-4d18-b44b-c1be03c4b039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>90b42b42-f281-430c-a2e2-b91d63bf0a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Salary'])[2]/preceding::span[1]</value>
      <webElementGuid>82c0c1ce-5c74-471f-b341-14763f93077a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Should be a positive number with at most 2 decimal places']/parent::*</value>
      <webElementGuid>31650fd7-3358-41f1-a154-1abfff19f674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//materializecss-decorator[2]/div/sf-decorator/div/span</value>
      <webElementGuid>4d2c75bf-cbb9-4a6e-af3d-c076e6ac704d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Should be a positive number with at most 2 decimal places' or . = 'Should be a positive number with at most 2 decimal places')]</value>
      <webElementGuid>b14df810-f9c0-4e85-917a-88dc886c08a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
