<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Should be less than 1,000,000,000</name>
   <tag></tag>
   <elementGuidId>e50d8e91-936b-4b5f-a3ea-7f9f47f99e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div/div/materializecss-decorator[2]/div/sf-decorator/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>materializecss-decorator:nth-of-type(2) > div.schema-form-section.row > sf-decorator > div.input-field.col.s12.m12.l12 > span.help-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Should be less than 1,000,000,000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2fd4b19-deb2-4bd6-acfb-1da35daa4343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>61c59a15-5ef4-40c6-93cd-cdd29cab3cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-message</name>
      <type>Main</type>
      <value>form.description</value>
      <webElementGuid>e8e70037-b856-44db-a449-3a08ba4fd7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Should be less than 1,000,000,000</value>
      <webElementGuid>4668aa0f-fe51-4c22-ad2c-70572522a079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-dirty ng-valid-parse ng-invalid ng-invalid-max ng-invalid-schema-form ng-invalid-lower-than-minimum ng-invalid-numeric-positive&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/materializecss-decorator[2]/div[@class=&quot;schema-form-section row&quot;]/sf-decorator[1]/div[@class=&quot;input-field col s12 m12 l12&quot;]/span[@class=&quot;help-block&quot;]</value>
      <webElementGuid>84d04a7d-cb96-4f4d-b6d8-ab215b6d0512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div/div/materializecss-decorator[2]/div/sf-decorator/div/span</value>
      <webElementGuid>d1c052a7-b7ce-4a6e-9f21-5f6d5a0b9f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Salary'])[2]/following::span[1]</value>
      <webElementGuid>437e969c-cbfd-4f6e-a367-0fe4b59c44bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>b3b1a3c6-aeb6-431c-8c04-378c40a6d89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Salary'])[2]/preceding::span[1]</value>
      <webElementGuid>4f972823-3ae0-4493-84ea-6cbd11be6eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Should be higher than Minimum Salary'])[1]/preceding::span[1]</value>
      <webElementGuid>7571116e-a3f1-44fb-bdf3-0f37144d1977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Should be less than 1,000,000,000']/parent::*</value>
      <webElementGuid>0e9f3898-7b5a-49e5-bf1f-389d51a4c6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//materializecss-decorator[2]/div/sf-decorator/div/span</value>
      <webElementGuid>2495ab8e-9e42-4c27-8ddd-150c2b9c8bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Should be less than 1,000,000,000' or . = 'Should be less than 1,000,000,000')]</value>
      <webElementGuid>5b41c2a3-4b57-453f-9c05-bf8e444be7cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
