<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Chief Executive Officer (C.E.O)</name>
   <tag></tag>
   <elementGuidId>c06b0bf9-11de-4fff-b986-596541fdf99f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;payGradesDiv&quot;]/crud-panel/div/div/list/table/tbody/tr[1]/td[2]/ng-include/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;listField.name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Chief Executive Officer (C.E.O)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c0540bc9-e240-4c94-9464-1ad540a9a713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>((obj[list.clickableCondition] &amp;&amp; list.clickableCondition)||!list.clickableCondition) &amp;&amp; (listField.hideField==true?false:true)</value>
      <webElementGuid>0e97a0af-5d5c-4c56-a823-90eb79d405cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>listField in listData.listFields</value>
      <webElementGuid>a0ff808e-0087-4d1f-b3e0-46472cf65763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>getStyle(obj, listField.style)</value>
      <webElementGuid>cc282b5a-47bb-4cc1-ba9b-971b37de68b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{truncate: listField.truncate, tooltipped: listField.truncate, 'cursor-pointer': listField.clickAction}</value>
      <webElementGuid>dfd8d3f9-9f1b-4d8b-998c-305f4bfba315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-data-tooltip</name>
      <type>Main</type>
      <value>{{listField.truncate ? getFieldValue(obj, listField.getter, listField.formatter, listField.filters) : undefined}}</value>
      <webElementGuid>cf668113-dce9-4228-8d21-5a031ef6536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-data-position</name>
      <type>Main</type>
      <value>{{listField.truncate ? 'bottom' : undefined}}</value>
      <webElementGuid>ab279f9d-b642-47d3-9a25-b5d273f390dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>list.runAction(listField.clickAction, obj, listField)</value>
      <webElementGuid>50c51f29-f664-44b8-bb2a-2e6d05e7168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>getFieldValue(obj, listField.getter, listField.formatter, listField.filters)</value>
      <webElementGuid>80291924-f158-40e8-93dd-176287dccbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowid</name>
      <type>Main</type>
      <value>obj.id</value>
      <webElementGuid>323be6f9-8b8d-405f-b5aa-9fa973873023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listField.name</value>
      <webElementGuid>96dc6700-833e-472f-af87-dda78694b163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>listField.type</value>
      <webElementGuid>a768be2a-2ef5-433e-9091-dd0ad78b0c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>extracontroller</name>
      <type>Main</type>
      <value>extracontroller</value>
      <webElementGuid>9f5dbd12-e3e9-46d8-ac44-686269c2d632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>getFieldValue(obj, listField.getter, listField.formatter, listField.filters, listField.link)</value>
      <webElementGuid>4c611b62-cefc-456d-86ae-7b3d4ad1f7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chief Executive Officer (C.E.O)</value>
      <webElementGuid>0d1d4223-899c-4555-8890-d4a851c0f5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGradesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>5668e50f-f916-4b42-8547-b37c6e475a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@name='listField.name']</value>
      <webElementGuid>9a839a92-204b-4caf-9105-de61871267ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payGradesDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]</value>
      <webElementGuid>a3df2387-6765-4005-8182-a498b89c8738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::td[2]</value>
      <webElementGuid>63803795-e8f2-4832-b5af-7c2457a46de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::td[2]</value>
      <webElementGuid>f49d0767-0ec3-43b6-9ed2-6d2561142569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::td[2]</value>
      <webElementGuid>04719928-d34c-4182-a6b4-d9360d1170a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>a912fbab-f0fa-4d2e-8819-2d69d155587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@name = 'listField.name' and @type = 'listField.type' and (text() = 'Chief Executive Officer (C.E.O)' or . = 'Chief Executive Officer (C.E.O)')]</value>
      <webElementGuid>09860e11-df31-48d0-80a7-749242dde475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
